 export const tests: any[] = [
    {
        "CLAVE_INSTITUCIONAL": "01PT1001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "01PT1001",
        "DESCRIPCION": "Acido Ascorbico (1g /10comp eferv)",
        "NOMBRE_GENERICO": "Acido Ascorbico",
        "PRESENTACION": "1g /10comp eferv",
        "MARCA_COMERCIAL": "Adriphel",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "01PT2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "01PT2001",
        "DESCRIPCION": "Acido Ascorbico (2g /10comp eferv)",
        "NOMBRE_GENERICO": "Acido Ascorbico",
        "PRESENTACION": "2g /10comp eferv",
        "MARCA_COMERCIAL": "Adriphel",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "23PT1001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "23PT1001",
        "DESCRIPCION": "Acido Ascorbico (2g/2tub/15comp eferv)",
        "NOMBRE_GENERICO": "Acido Ascorbico",
        "PRESENTACION": "2g/2tub/15comp eferv",
        "MARCA_COMERCIAL": "Adriphel",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "34PT1003",
        "AGRUPADOR": null,
        "ID_SISTEMA": "34PT1003",
        "DESCRIPCION": "Acido Ascorbico (Presentacion Desconocida)",
        "NOMBRE_GENERICO": "Acido Ascorbico",
        "PRESENTACION": "Presentacion Desconocida",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "46PT1001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "46PT1001",
        "DESCRIPCION": "Acido Ascorbico/Zinc (1g/10mg/10comp eferv)",
        "NOMBRE_GENERICO": "Acido Ascorbico/Zinc",
        "PRESENTACION": "1g/10mg/10comp eferv",
        "MARCA_COMERCIAL": "Vangrish Z",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "46PT2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "46PT2001",
        "DESCRIPCION": "Acido Ascorbico/Zinc (1g/10mg/15comp eferv)",
        "NOMBRE_GENERICO": "Acido Ascorbico/Zinc",
        "PRESENTACION": "1g/10mg/15comp eferv",
        "MARCA_COMERCIAL": "Vangrish Z",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "47PT1001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "47PT1001",
        "DESCRIPCION": "Acido Ascorbico/Zinc/Vitamina D3 (1g/10mg/400ui/10comp eferv)",
        "NOMBRE_GENERICO": "Acido Ascorbico/Zinc/Vitamina D3",
        "PRESENTACION": "1g/10mg/400ui/10comp eferv",
        "MARCA_COMERCIAL": "Vandrifel",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "47PT2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "47PT2001",
        "DESCRIPCION": "Acido Ascorbico/Zinc/Vitamina D3 (600mg/6.2mg/400ui/15comp eferv)",
        "NOMBRE_GENERICO": "Acido Ascorbico/Zinc/Vitamina D3",
        "PRESENTACION": "600mg/6.2mg/400ui/15comp eferv",
        "MARCA_COMERCIAL": "Vandrifel",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.7021.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT32002",
        "DESCRIPCION": "Acido Tranexamico (1g/10via/10ml)",
        "NOMBRE_GENERICO": "Acido Tranexamico",
        "PRESENTACION": "1g/10via/10ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.7021.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT32003",
        "DESCRIPCION": "Acido Tranexamico (1g/10via/10ml)",
        "NOMBRE_GENERICO": "Acido Tranexamico",
        "PRESENTACION": "1g/10via/10ml",
        "MARCA_COMERCIAL": "Tramuvan",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.7021.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT32001",
        "DESCRIPCION": "Acido Tranexamico (500mg/10via/5ml)",
        "NOMBRE_GENERICO": "Acido Tranexamico",
        "PRESENTACION": "500mg/10via/5ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.7021.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT32004",
        "DESCRIPCION": "Acido Tranexamico (500mg/10via/5ml)",
        "NOMBRE_GENERICO": "Acido Tranexamico",
        "PRESENTACION": "500mg/10via/5ml",
        "MARCA_COMERCIAL": "Tramuvan",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.6298.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "040.000.2500.00",
        "DESCRIPCION": "Alprazolam (0.25mg/30tabl)",
        "NOMBRE_GENERICO": "Alprazolam",
        "PRESENTACION": "0.25mg/30tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": "Inconsistencia Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.6298.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "040.000.2500.00",
        "DESCRIPCION": "Alprazolam (0.25mg/30tabl)",
        "NOMBRE_GENERICO": "Alprazolam",
        "PRESENTACION": "0.25mg/30tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6051.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT14001",
        "DESCRIPCION": "Alprostadil (0.5mg/5amp/1ml)",
        "NOMBRE_GENERICO": "Alprostadil",
        "PRESENTACION": "0.5mg/5amp/1ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6051.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT14002",
        "DESCRIPCION": "Alprostadil (0.5mg/5amp/1ml)",
        "NOMBRE_GENERICO": "Alprostadil",
        "PRESENTACION": "0.5mg/5amp/1ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1224.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Aluminio/Magnesio (3.7mg/4g/100ml)",
        "NOMBRE_GENERICO": "Aluminio/Magnesio",
        "PRESENTACION": "3.7mg/4g/100ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1224.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Aluminio/Magnesio (3.7mg/4g/100ml)",
        "NOMBRE_GENERICO": "Aluminio/Magnesio",
        "PRESENTACION": "3.7mg/4g/100ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": null,
        "AGRUPADOR": null,
        "ID_SISTEMA": "010.000.1223.00",
        "DESCRIPCION": "Aluminio/Magnesio (50tabl)",
        "NOMBRE_GENERICO": "Aluminio/Magnesio",
        "PRESENTACION": "50tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": "Inconsistencia Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": null,
        "AGRUPADOR": null,
        "ID_SISTEMA": "010.000.1223.00",
        "DESCRIPCION": "Aluminio/Magnesio (50tabl)",
        "NOMBRE_GENERICO": "Aluminio/Magnesio",
        "PRESENTACION": "50tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.2111.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "40PT1003                       ",
        "DESCRIPCION": "Amlodipino (5mg/30tabl)",
        "NOMBRE_GENERICO": "Amlodipino",
        "PRESENTACION": "5mg/30tabl",
        "MARCA_COMERCIAL": "Aldromasil",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.2111.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "40PT1004",
        "DESCRIPCION": "Amlodipino (5mg/30tabl)",
        "NOMBRE_GENERICO": "Amlodipino",
        "PRESENTACION": "5mg/30tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.3461.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT21001",
        "DESCRIPCION": "Azatioprina (50mg/50tabl)",
        "NOMBRE_GENERICO": "Azatioprina",
        "PRESENTACION": "50mg/50tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.3461.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT21001",
        "DESCRIPCION": "Azatioprina (50mg/50tabl)",
        "NOMBRE_GENERICO": "Azatioprina",
        "PRESENTACION": "50mg/50tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5331.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT54001",
        "DESCRIPCION": "Beractant (25mg/via)",
        "NOMBRE_GENERICO": "Beractant",
        "PRESENTACION": "25mg/via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5331.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT54001",
        "DESCRIPCION": "Beractant (25mg/via)",
        "NOMBRE_GENERICO": "Beractant",
        "PRESENTACION": "25mg/via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6307.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT28001",
        "DESCRIPCION": "Busulfan (6mg/1via)",
        "NOMBRE_GENERICO": "Busulfan",
        "PRESENTACION": "6mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6307.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT28001",
        "DESCRIPCION": "Busulfan (6mg/1via)",
        "NOMBRE_GENERICO": "Busulfan",
        "PRESENTACION": "6mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6083.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT13001",
        "DESCRIPCION": "Cafeina Citrato (20mg/10via)",
        "NOMBRE_GENERICO": "Cafeina Citrato",
        "PRESENTACION": "20mg/10via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6083.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT13001",
        "DESCRIPCION": "Cafeina Citrato (20mg/10via)",
        "NOMBRE_GENERICO": "Cafeina Citrato",
        "PRESENTACION": "20mg/10via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "43PT2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "43PT2001",
        "DESCRIPCION": "Calcio/Vitamina D3 (600mg/400ui/12fco/180tabl)",
        "NOMBRE_GENERICO": "Calcio/Vitamina D3",
        "PRESENTACION": "600mg/400ui/12fco/180tabl",
        "MARCA_COMERCIAL": "Kirkland",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "43PT1001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "43PT1001",
        "DESCRIPCION": "Calcio/Vitamina D3 (600mg/400ui/180tabl)",
        "NOMBRE_GENERICO": "Calcio/Vitamina D3",
        "PRESENTACION": "600mg/400ui/180tabl",
        "MARCA_COMERCIAL": "Kirkland",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6000.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "26PT1001",
        "DESCRIPCION": "Carbonato de Calcio/Vitamina D3 (600mg/400ui/30tabl)",
        "NOMBRE_GENERICO": "Carbonato de Calcio/Vitamina D3",
        "PRESENTACION": "600mg/400ui/30tabl",
        "MARCA_COMERCIAL": "Flucaten - D",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6000.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "26PT1002",
        "DESCRIPCION": "Carbonato de Calcio/Vitamina D3 (600mg/400ui/30tabl)",
        "NOMBRE_GENERICO": "Carbonato de Calcio/Vitamina D3",
        "PRESENTACION": "600mg/400ui/30tabl",
        "MARCA_COMERCIAL": "Flucaten - D",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.3255.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT36001",
        "DESCRIPCION": "Carbonato de Litio (300mg/50tabl)",
        "NOMBRE_GENERICO": "Carbonato de Litio",
        "PRESENTACION": "300mg/50tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.3255.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT36001",
        "DESCRIPCION": "Carbonato de Litio (300mg/50tabl)",
        "NOMBRE_GENERICO": "Carbonato de Litio",
        "PRESENTACION": "300mg/50tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "060.203.0561",
        "AGRUPADOR": null,
        "ID_SISTEMA": "060.203.0561",
        "DESCRIPCION": "Cinta (Longitud 9-9.5m Ancho 5.0cm)",
        "NOMBRE_GENERICO": "Cinta",
        "PRESENTACION": "Longitud 9-9.5m Ancho 5.0cm",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "060.203.0579",
        "AGRUPADOR": null,
        "ID_SISTEMA": "060.203.0579",
        "DESCRIPCION": "Cinta (Longitud 9-9.5m Ancho 7.5cm)",
        "NOMBRE_GENERICO": "Cinta",
        "PRESENTACION": "Longitud 9-9.5m Ancho 7.5cm",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6322.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT52001",
        "DESCRIPCION": "Cladribina (10mg/1comp)",
        "NOMBRE_GENERICO": "Cladribina",
        "PRESENTACION": "10mg/1comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.6322.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT52001",
        "DESCRIPCION": "Cladribina (10mg/1comp)",
        "NOMBRE_GENERICO": "Cladribina",
        "PRESENTACION": "10mg/1comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.5351.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "040.000.5351.00",
        "DESCRIPCION": "Clorhidrato de Metilfenidato (10mg)",
        "NOMBRE_GENERICO": "Clorhidrato de Metilfenidato",
        "PRESENTACION": "10mg",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.5351.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "040.000.5351.00",
        "DESCRIPCION": "Clorhidrato de Metilfenidato (10mg)",
        "NOMBRE_GENERICO": "Clorhidrato de Metilfenidato",
        "PRESENTACION": "10mg",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.2154.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10004",
        "DESCRIPCION": "Enoxaparina Sodica (40mg/2jer)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "40mg/2jer",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.2154.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10004",
        "DESCRIPCION": "Enoxaparina Sodica (40mg/2jer)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "40mg/2jer",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4224.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10007",
        "DESCRIPCION": "Enoxaparina Sodica (60mg/2jer/0.6ml)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "60mg/2jer/0.6ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4224.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10007",
        "DESCRIPCION": "Enoxaparina Sodica (60mg/2jer/0.6ml)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "60mg/2jer/0.6ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4224.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10001",
        "DESCRIPCION": "Enoxaparina Sodica (60mg/2via)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "60mg/2via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4224.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10001",
        "DESCRIPCION": "Enoxaparina Sodica (60mg/2via)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "60mg/2via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5931.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10002",
        "DESCRIPCION": "Enoxaparina Sodica (80mg/2jer)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "80mg/2jer",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5931.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT10002",
        "DESCRIPCION": "Enoxaparina Sodica (80mg/2jer)",
        "NOMBRE_GENERICO": "Enoxaparina Sodica",
        "PRESENTACION": "80mg/2jer",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1773.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT11002",
        "DESCRIPCION": "Epirubicina (10mg/1via)",
        "NOMBRE_GENERICO": "Epirubicina",
        "PRESENTACION": "10mg/1via",
        "MARCA_COMERCIAL": "Herossa",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1773.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT11002",
        "DESCRIPCION": "Epirubicina (10mg/1via)",
        "NOMBRE_GENERICO": "Epirubicina",
        "PRESENTACION": "10mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1774.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT11003",
        "DESCRIPCION": "Epirubicina (50mg/1amp/25ml)",
        "NOMBRE_GENERICO": "Epirubicina",
        "PRESENTACION": "50mg/1amp/25ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1774.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT11001",
        "DESCRIPCION": "Epirubicina (50mg/1via)",
        "NOMBRE_GENERICO": "Epirubicina",
        "PRESENTACION": "50mg/1via",
        "MARCA_COMERCIAL": "Herossa",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.2156.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT50001",
        "DESCRIPCION": "Espironolactona (100mg/30tabl)",
        "NOMBRE_GENERICO": "Espironolactona",
        "PRESENTACION": "100mg/30tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.2156.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT50001",
        "DESCRIPCION": "Espironolactona (100mg/30tabl)",
        "NOMBRE_GENERICO": "Espironolactona",
        "PRESENTACION": "100mg/30tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": null,
        "AGRUPADOR": null,
        "ID_SISTEMA": "010.000.2304.00",
        "DESCRIPCION": "Espironolactona (25mg/20tabl)",
        "NOMBRE_GENERICO": "Espironolactona",
        "PRESENTACION": "25mg/20tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": "Falta Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": null,
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Espironolactona (25mg/20tabl)",
        "NOMBRE_GENERICO": "Espironolactona",
        "PRESENTACION": "25mg/20tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Falta Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5651.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT29001",
        "DESCRIPCION": "Everolimus (5mg/30comp)",
        "NOMBRE_GENERICO": "Everolimus",
        "PRESENTACION": "5mg/30comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5651.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT29001",
        "DESCRIPCION": "Everolimus (5mg/30comp)",
        "NOMBRE_GENERICO": "Everolimus",
        "PRESENTACION": "5mg/30comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "03PTM4001",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Be Free W3-OE (16caj/60sticks/1.96g)",
        "NOMBRE_GENERICO": "Be Free W3-OE",
        "PRESENTACION": "16caj/60sticks/1.96g",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "03PTM2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "03PTM2001",
        "DESCRIPCION": "Be Free W3-OE (30sticks/1.96g)",
        "NOMBRE_GENERICO": "Be Free W3-OE",
        "PRESENTACION": "30sticks/1.96g",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "02PTM4001",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Be Free W2-MB (16caj/60amp/5ml)",
        "NOMBRE_GENERICO": "Be Free W2-MB",
        "PRESENTACION": "16caj/60amp/5ml",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "02PTM2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "02PTM2001",
        "DESCRIPCION": "Be Free W2-MB (30amp/5ml)",
        "NOMBRE_GENERICO": "Be Free W2-MB",
        "PRESENTACION": "30amp/5ml",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "04PTM4001",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Be Free W4-SC (16caj/60sticks/2.99g)",
        "NOMBRE_GENERICO": "Be Free W4-SC",
        "PRESENTACION": "16caj/60sticks/2.99g",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "04PTM2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "04PTM2001",
        "DESCRIPCION": "Be Free W4-SC (30sticks/2.99g)",
        "NOMBRE_GENERICO": "Be Free W4-SC",
        "PRESENTACION": "30sticks/2.99g",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "01PTM3001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "01PTM3001",
        "DESCRIPCION": "Be Free W1-VC (120caps)",
        "NOMBRE_GENERICO": "Be Free W1-VC",
        "PRESENTACION": "120caps",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "01PTM4001",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Be Free W1-VC  (16caj/120caps)",
        "NOMBRE_GENERICO": "Be Free W1-VC ",
        "PRESENTACION": "16caj/120caps",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "01PTM2001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "01PTM2001",
        "DESCRIPCION": "Be Free W1-VC (60caps)",
        "NOMBRE_GENERICO": "Be Free W1-VC",
        "PRESENTACION": "60caps",
        "MARCA_COMERCIAL": "Be Free",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "35PT49001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT49001",
        "DESCRIPCION": "Satial F (50g)",
        "NOMBRE_GENERICO": "Satial F",
        "PRESENTACION": "50g",
        "MARCA_COMERCIAL": "Satial F",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "35PT48001",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT48001",
        "DESCRIPCION": "Satial (600mg/30comp)",
        "NOMBRE_GENERICO": "Satial",
        "PRESENTACION": "600mg/30comp",
        "MARCA_COMERCIAL": "Satial F",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "35PT48002",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT48002",
        "DESCRIPCION": "Satial (600mg/60comp)",
        "NOMBRE_GENERICO": "Satial",
        "PRESENTACION": "600mg/60comp",
        "MARCA_COMERCIAL": "Satial F",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.0242.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT46001",
        "DESCRIPCION": "Fentanilo (0.5mg/6amp)",
        "NOMBRE_GENERICO": "Fentanilo",
        "PRESENTACION": "0.5mg/6amp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5880.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT30001",
        "DESCRIPCION": "Fulvestrant (250mg/2via)",
        "NOMBRE_GENERICO": "Fulvestrant",
        "PRESENTACION": "250mg/2via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5880.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT30001",
        "DESCRIPCION": "Fulvestrant (250mg/2via)",
        "NOMBRE_GENERICO": "Fulvestrant",
        "PRESENTACION": "250mg/2via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1006.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "03PT1012",
        "DESCRIPCION": "Gluconolactato de Calcio/Carbonato de Calcio (500mg/12tabl)",
        "NOMBRE_GENERICO": "Gluconolactato de Calcio/Carbonato de Calcio",
        "PRESENTACION": "500mg/12tabl",
        "MARCA_COMERCIAL": "Van-Cal",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1006.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "03PT1014",
        "DESCRIPCION": "Gluconolactato de Calcio/Carbonato de Calcio (500mg/12tabl)",
        "NOMBRE_GENERICO": "Gluconolactato de Calcio/Carbonato de Calcio",
        "PRESENTACION": "500mg/12tabl",
        "MARCA_COMERCIAL": "Van-Cal",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4229.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT23001",
        "DESCRIPCION": "L-Asparaginasa (10,000ui/1via)",
        "NOMBRE_GENERICO": "L-Asparaginasa",
        "PRESENTACION": "10,000ui/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4229.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT23001",
        "DESCRIPCION": "L-Asparaginasa (10,000ui/1via)",
        "NOMBRE_GENERICO": "L-Asparaginasa",
        "PRESENTACION": "10,000ui/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5097.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT35001",
        "DESCRIPCION": "Levosimendan (2.5mg/1amp/5ml)",
        "NOMBRE_GENERICO": "Levosimendan",
        "PRESENTACION": "2.5mg/1amp/5ml",
        "MARCA_COMERCIAL": "Alvan",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5097.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT35001",
        "DESCRIPCION": "Levosimendan (2.5mg/1amp/5ml)",
        "NOMBRE_GENERICO": "Levosimendan",
        "PRESENTACION": "2.5mg/1amp/5ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.2520.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Losartan (150mg/30comp)",
        "NOMBRE_GENERICO": "Losartan",
        "PRESENTACION": "150mg/30comp",
        "MARCA_COMERCIAL": "Targancil",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Inconsistencia Item Number"
    },
    {
        "CLAVE_INSTITUCIONAL": "39PT1002",
        "AGRUPADOR": null,
        "ID_SISTEMA": "39PT1002",
        "DESCRIPCION": "Losartan (50mg/30comp)",
        "NOMBRE_GENERICO": "Losartan",
        "PRESENTACION": "50mg/30comp",
        "MARCA_COMERCIAL": "Targancil",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Falta Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": null,
        "AGRUPADOR": null,
        "ID_SISTEMA": "39PT1001",
        "DESCRIPCION": "Losartan (50mg/30comp)",
        "NOMBRE_GENERICO": "Losartan",
        "PRESENTACION": "50mg/30comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": "Falta Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1761.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT20001",
        "DESCRIPCION": "Mercaptopurina (50mg/25tabl)",
        "NOMBRE_GENERICO": "Mercaptopurina",
        "PRESENTACION": "50mg/25tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.1761.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT20001",
        "DESCRIPCION": "Mercaptopurina (50mg/25tabl)",
        "NOMBRE_GENERICO": "Mercaptopurina",
        "PRESENTACION": "50mg/25tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "20PT1006",
        "AGRUPADOR": null,
        "ID_SISTEMA": "20PT1006",
        "DESCRIPCION": "Misoprostol (200mcg/12tabl)",
        "NOMBRE_GENERICO": "Misoprostol",
        "PRESENTACION": "200mcg/12tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "20PT1012",
        "AGRUPADOR": null,
        "ID_SISTEMA": "20PT1012",
        "DESCRIPCION": "Misoprostol (200mcg/1tabl)",
        "NOMBRE_GENERICO": "Misoprostol",
        "PRESENTACION": "200mcg/1tabl",
        "MARCA_COMERCIAL": "Tomispral",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "20PT1017",
        "AGRUPADOR": null,
        "ID_SISTEMA": "20PT1017",
        "DESCRIPCION": "Misoprostol (200mcg/1tabl)",
        "NOMBRE_GENERICO": "Misoprostol",
        "PRESENTACION": "200mcg/1tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": null,
        "AGRUPADOR": null,
        "ID_SISTEMA": "20PT1008",
        "DESCRIPCION": "Misoprostol (200mcg/8tabl)",
        "NOMBRE_GENERICO": "Misoprostol",
        "PRESENTACION": "200mcg/8tabl",
        "MARCA_COMERCIAL": "Tomispral",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Falta Clave Institucional"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.0599.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "33PT1002",
        "DESCRIPCION": "Nifedipino (30mg/30comp)",
        "NOMBRE_GENERICO": "Nifedipino",
        "PRESENTACION": "30mg/30comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "33PT1002",
        "AGRUPADOR": null,
        "ID_SISTEMA": "33PT1002",
        "DESCRIPCION": "Nifedipino (30mg/30comp)",
        "NOMBRE_GENERICO": "Nifedipino",
        "PRESENTACION": "30mg/30comp",
        "MARCA_COMERCIAL": "Notinzalten",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "33PT1004",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Nifedipino (30mg/30comp)",
        "NOMBRE_GENERICO": "Nifedipino",
        "PRESENTACION": "30mg/30comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": "Distribuidor",
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Falta Clave Institucional / Inconsistencia en Item number"
    },
    {
        "CLAVE_INSTITUCIONAL": "33PT1006",
        "AGRUPADOR": null,
        "ID_SISTEMA": "33PT1006",
        "DESCRIPCION": "Nifedipino (30mg/30comp)",
        "NOMBRE_GENERICO": "Nifedipino",
        "PRESENTACION": "30mg/30comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "33PT1008",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Nifedipino (30mg/30comp)",
        "NOMBRE_GENERICO": "Nifedipino",
        "PRESENTACION": "30mg/30comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": "Distribuidor",
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": "Falta Clave Institucional / Inconsistencia en Item number"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5459.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT16001",
        "DESCRIPCION": "Oxaliplatino (100mg/1via)",
        "NOMBRE_GENERICO": "Oxaliplatino",
        "PRESENTACION": "100mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": null,
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5459.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT16004",
        "DESCRIPCION": "Oxaliplatino (100mg/1via)",
        "NOMBRE_GENERICO": "Oxaliplatino",
        "PRESENTACION": "100mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": null,
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "35PT16006",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT16006",
        "DESCRIPCION": "Oxaliplatino (100mg/1fco/20ml)",
        "NOMBRE_GENERICO": "Oxaliplatino",
        "PRESENTACION": "100mg/1fco/20ml",
        "MARCA_COMERCIAL": "Recoxtin",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5458.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT16003",
        "DESCRIPCION": "Oxaliplatino (50mg/1via)",
        "NOMBRE_GENERICO": "Oxaliplatino",
        "PRESENTACION": "50mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5458.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT16003",
        "DESCRIPCION": "Oxaliplatino (50mg/1via)",
        "NOMBRE_GENERICO": "Oxaliplatino",
        "PRESENTACION": "50mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "35PT16005",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT16005",
        "DESCRIPCION": "Oxaliplatino (50mg/1fco/10ml)",
        "NOMBRE_GENERICO": "Oxaliplatino",
        "PRESENTACION": "50mg/1fco/10ml",
        "MARCA_COMERCIAL": "Recoxtin",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5307.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT12001",
        "DESCRIPCION": "Plerixafor (24mg/1via)",
        "NOMBRE_GENERICO": "Plerixafor",
        "PRESENTACION": "24mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5307.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT12001",
        "DESCRIPCION": "Plerixafor (24mg/1via)",
        "NOMBRE_GENERICO": "Plerixafor",
        "PRESENTACION": "24mg/1via",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.0244.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT17001",
        "DESCRIPCION": "Propofol (200mg/5amp/20ml)",
        "NOMBRE_GENERICO": "Propofol",
        "PRESENTACION": "200mg/5amp/20ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.0244.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT17001",
        "DESCRIPCION": "Propofol (200mg/5amp/20ml)",
        "NOMBRE_GENERICO": "Propofol",
        "PRESENTACION": "200mg/5amp/20ml",
        "MARCA_COMERCIAL": "Quishvan",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "38PT2002",
        "AGRUPADOR": null,
        "ID_SISTEMA": null,
        "DESCRIPCION": "Propofol (200mg/5amp/20ml)",
        "NOMBRE_GENERICO": "Propofol",
        "PRESENTACION": "200mg/5amp/20ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": null,
        "OBSERVACIONES": "Falta Clave Institucional / Inconsistencia en Item number"
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5494.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT51001",
        "DESCRIPCION": "Quetiapina (300mg/30tabl XR)",
        "NOMBRE_GENERICO": "Quetiapina",
        "PRESENTACION": "300mg/30tabl XR",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5494.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT51001",
        "DESCRIPCION": "Quetiapina (300mg/30tabl XR)",
        "NOMBRE_GENERICO": "Quetiapina",
        "PRESENTACION": "300mg/30tabl XR",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.3258.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "12PT2011",
        "DESCRIPCION": "Risperidona (2mg/40tabl)",
        "NOMBRE_GENERICO": "Risperidona",
        "PRESENTACION": "2mg/40tabl",
        "MARCA_COMERCIAL": "Lost Per",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.3258.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "12PT2011",
        "DESCRIPCION": "Risperidona (2mg/40tabl)",
        "NOMBRE_GENERICO": "Risperidona",
        "PRESENTACION": "2mg/40tabl",
        "MARCA_COMERCIAL": "Lost Per",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.3268.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "12PT2005",
        "DESCRIPCION": "Risperidona (25mg/1fco-1jer/2ml)",
        "NOMBRE_GENERICO": "Risperidona",
        "PRESENTACION": "25mg/1fco-1jer/2ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "040.000.3268.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "12PT2005",
        "DESCRIPCION": "Risperidona (25mg/1fco-1jer/2ml)",
        "NOMBRE_GENERICO": "Risperidona",
        "PRESENTACION": "25mg/1fco-1jer/2ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5703.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT45001",
        "DESCRIPCION": "Sitagliptina/Metformina (50mg/850mg/56tabl)",
        "NOMBRE_GENERICO": "Sitagliptina/Metformina",
        "PRESENTACION": "50mg/850mg/56tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5703.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT45001",
        "DESCRIPCION": "Sitagliptina/Metformina (50mg/850mg/56tabl)",
        "NOMBRE_GENERICO": "Sitagliptina/Metformina",
        "PRESENTACION": "50mg/850mg/56tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5084.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15004",
        "DESCRIPCION": "Tacrolimus (1mg/100caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "1mg/100caps",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5084.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15004",
        "DESCRIPCION": "Tacrolimus (1mg/100caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "1mg/100caps",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5084.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15002",
        "DESCRIPCION": "Tacrolimus (1mg/50caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "1mg/50caps",
        "MARCA_COMERCIAL": "Vangorn",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5084.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15002",
        "DESCRIPCION": "Tacrolimus (1mg/50caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "1mg/50caps",
        "MARCA_COMERCIAL": "Vangorn",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5082.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15001",
        "DESCRIPCION": "Tacrolimus (5mg/100caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "5mg/100caps",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5082.01",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15001",
        "DESCRIPCION": "Tacrolimus (5mg/100caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "5mg/100caps",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5082.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15003",
        "DESCRIPCION": "Tacrolimus (5mg/50caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "5mg/50caps",
        "MARCA_COMERCIAL": "Vangorn",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5082.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT15003",
        "DESCRIPCION": "Tacrolimus (5mg/50caps)",
        "NOMBRE_GENERICO": "Tacrolimus",
        "PRESENTACION": "5mg/50caps",
        "MARCA_COMERCIAL": "Vangorn",
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4578.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT24001",
        "DESCRIPCION": "Teicoplanina (400mg/1fco-1amp/3ml)",
        "NOMBRE_GENERICO": "Teicoplanina",
        "PRESENTACION": "400mg/1fco-1amp/3ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.4578.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT24001",
        "DESCRIPCION": "Teicoplanina (400mg/1fco-1amp/3ml)",
        "NOMBRE_GENERICO": "Teicoplanina",
        "PRESENTACION": "400mg/1fco-1amp/3ml",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.7018.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT37001",
        "DESCRIPCION": "Tetrabenazina (25mg/112comp)",
        "NOMBRE_GENERICO": "Tetrabenazina",
        "PRESENTACION": "25mg/112comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.7018.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT37001",
        "DESCRIPCION": "Tetrabenazina (25mg/112comp)",
        "NOMBRE_GENERICO": "Tetrabenazina",
        "PRESENTACION": "25mg/112comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "32PT1002",
        "AGRUPADOR": null,
        "ID_SISTEMA": "32PT10002",
        "DESCRIPCION": "Tetrabenazina (25mg/28comp)",
        "NOMBRE_GENERICO": "Tetrabenazina",
        "PRESENTACION": "25mg/28comp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5337.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT26001",
        "DESCRIPCION": "Tobramicina (300mg/14sob/4amp)",
        "NOMBRE_GENERICO": "Tobramicina",
        "PRESENTACION": "300mg/14sob/4amp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5337.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "35PT26001",
        "DESCRIPCION": "Tobramicina (300mg/14sob/4amp)",
        "NOMBRE_GENERICO": "Tobramicina",
        "PRESENTACION": "300mg/14sob/4amp",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5363.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "27PT3002",
        "DESCRIPCION": "Topiramato (100mg/60tabl)",
        "NOMBRE_GENERICO": "Topiramato",
        "PRESENTACION": "100mg/60tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Privada",
        "OBSERVACIONES": null
    },
    {
        "CLAVE_INSTITUCIONAL": "010.000.5363.00",
        "AGRUPADOR": null,
        "ID_SISTEMA": "27PT3002",
        "DESCRIPCION": "Topiramato (100mg/60tabl)",
        "NOMBRE_GENERICO": "Topiramato",
        "PRESENTACION": "100mg/60tabl",
        "MARCA_COMERCIAL": null,
        "TIPO_CLIENTE": null,
        "TIPO_VENTA": "Publica",
        "OBSERVACIONES": null
    }
]


